-- ============================================================
-- Centro de control de mensajes / alertas operativas (WhatsApp)
-- Ejecutar en Supabase SQL Editor. Idempotente.
-- ============================================================
-- Modelo:
--   • alerta_destinatarios : directorio editable de personas que reciben alertas
--     (nombre + función + WhatsApp). El usuario los administra desde la UI.
--   • alerta_config        : una fila por TIPO de mensaje, con su activación, cuándo
--     se envía (evento / anticipación en min / hora fija) y a quién (conductor,
--     pasajero, y qué contactos del directorio via `destinatarios` jsonb de ids).
--   • avisos_conductor_estado : dedupe de las alertas de ciclo de vida por reserva.
-- El motor (/api/alertas-flota/tick) lee esta config; nada está hardcodeado.
-- ============================================================

-- ── 1) Directorio de destinatarios ────────────────────────────────────────────
create table if not exists public.alerta_destinatarios (
  id              bigint generated by default as identity primary key,
  nombre          text not null,
  funcion         text,                  -- p.ej. "Coordinador de Operaciones", "Administración"
  telefono        text not null,         -- WhatsApp E.164 o 9 dígitos (se normaliza al enviar)
  activo          boolean not null default true,
  es_contingencia boolean not null default false, -- su número aparece en los mensajes al conductor
  created_at      timestamptz default now()
);
alter table public.alerta_destinatarios add column if not exists es_contingencia boolean not null default false;

-- ── 2) Configuración por tipo de mensaje ──────────────────────────────────────
create table if not exists public.alerta_config (
  clave               text primary key,          -- id estable del tipo de alerta
  nombre              text not null,              -- etiqueta visible
  descripcion         text,
  activo              boolean not null default true,
  -- Cuándo se envía:
  modo_tiempo         text not null default 'evento'
                      check (modo_tiempo in ('evento','anticipacion','hora_fija')),
  min_anticipacion    int,                        -- modo 'anticipacion': X min antes del servicio
  hora_fija           text,                       -- modo 'hora_fija': "HH:MM" (Lima)
  umbral              int,                         -- genérico: gracia(min) / silencio(min) / días
  -- A quién:
  notifica_conductor  boolean not null default false,
  notifica_pasajero   boolean not null default false,
  destinatarios       jsonb not null default '[]'::jsonb,  -- ids de alerta_destinatarios
  -- Plantillas Meta (por nombre; deben existir/estar aprobadas):
  plantilla           text,                        -- para conductor/pasajero
  plantilla_directorio text default 'coordinador_alerta', -- para el personal del directorio
  updated_at          timestamptz default now()
);

-- Semilla de todos los tipos con defaults razonables (no re-piso lo que el usuario edite).
insert into public.alerta_config
  (clave, nombre, descripcion, modo_tiempo, min_anticipacion, hora_fija, umbral,
   notifica_conductor, notifica_pasajero, plantilla)
values
  ('recordatorio_pasajero','Recordatorio al pasajero','Aviso del servicio al pasajero','hora_fija',null,'08:00',null,
     false,true,'recordatorio_servicio'),
  ('recordatorio_conductor','Recordatorio al conductor','Aviso del servicio asignado (mismo contenido que "Servicio asignado")','anticipacion',720,null,null,
     true,false,'recordatorio_conductor'),
  ('proximo_inicio','Próximo a iniciar','Aviso corto y urgente justo antes del servicio','anticipacion',90,null,null,
     true,false,'conductor_proximo_inicio'),
  ('asignacion','Servicio asignado','Cuando se le asigna un servicio al conductor','evento',null,null,null,
     true,false,'recordatorio_conductor'),
  ('cambio','Cambio de servicio','Cuando cambia la hora o el vehículo','evento',null,null,null,
     true,false,'conductor_cambio_servicio'),
  ('cancelacion','Servicio cancelado','Cuando se cancela un servicio asignado','evento',null,null,null,
     true,false,'conductor_servicio_cancelado'),
  ('desasignacion','Servicio reasignado (aviso al saliente)','Avisa al conductor anterior que ya no cubre el servicio','evento',null,null,null,
     true,false,'conductor_desasignado'),
  ('no_inicio','No inició a tiempo','El conductor no marcó inicio pasada la hora','evento',null,null,10,
     true,false,'conductor_no_inicio'),
  ('gps_silencio','GPS sin señal','Una unidad en curso dejó de enviar ubicación','evento',null,null,8,
     true,false,'conductor_gps_silencio'),
  ('doc_vence','Documento por vencer','Documentos del conductor próximos a vencer','hora_fija',null,'08:00',15,
     true,false,'conductor_doc_vence'),
  ('solape','Solape de conductor','Un conductor con servicios que se cruzan','hora_fija',null,'07:00',null,
     false,false,'coordinador_alerta'),
  ('jornada','Jornada extensa','Conductor con jornada larga o muchos servicios','hora_fija',null,'07:00',13,
     false,false,'coordinador_alerta')
on conflict (clave) do nothing;

-- ── 3) Dedupe de alertas de ciclo de vida (una fila por reserva) ──────────────
create table if not exists public.avisos_conductor_estado (
  reserva_id          bigint primary key,
  conductor_avisado   bigint,
  vehiculo_avisado    bigint,
  hora_avisada        text,
  cancelacion_avisada boolean not null default false,
  aviso_90_at         timestamptz,      -- recordatorio por anticipación ya enviado
  no_inicio_at        timestamptz,
  gps_silencio_at     timestamptz,      -- null = GPS ok / re-armado
  updated_at          timestamptz default now()
);

-- BACKFILL de baseline: siembra el estado de las reservas YA asignadas al correr la
-- migración por PRIMERA vez, para que el PRIMER tick NO las trate como "asignación nueva"
-- y dispare un blast masivo de WhatsApp. Solo corre si la tabla está VACÍA: así re-ejecutar
-- la migración (con el sistema ya en producción) NO siembra baseline de reservas nuevas
-- —que aún no fueron notificadas— y por tanto no les suprime su aviso de asignación real.
do $$
begin
  if not exists (select 1 from public.avisos_conductor_estado) then
    insert into public.avisos_conductor_estado (reserva_id, conductor_avisado, vehiculo_avisado, hora_avisada)
    select id, conductor_id, vehiculo_id, coalesce(substr(hora_servicio::text, 1, 5), '-')
    from public.reservas
    where tipo_asignacion = 'propio' and conductor_id is not null and estado <> 'cancelada';
  end if;
end$$;

-- ── 3b) Dedupe universal insert-once (avisos por día: recordatorios, docs, solape,
--       jornada). ref = reserva_id / conductor_id / "conductor_id:doc" según el tipo.
--       El motor inserta y un 23505 significa "ya se envió hoy" → no reenvía.
create table if not exists public.alerta_enviada (
  id         bigint generated by default as identity primary key,
  clave      text not null,
  ref        text not null,
  fecha      date not null,
  created_at timestamptz default now()
);
create unique index if not exists uq_alerta_enviada on public.alerta_enviada(clave, ref, fecha);

-- ── 3c) Canales de notificación al PASAJERO (anti-spam) ───────────────────────
--   Los avisos al pasajero (confirmación, recordatorio, "bus llegó") salían SIEMPRE
--   por los 3 canales (push app + email + WhatsApp) = spam. Aquí se controla cada
--   canal y, con "solo_sin_app", se manda ese canal ÚNICAMENTE a quien NO tiene la
--   app (sin suscripción push activa). Default: con app → solo push; sin app → email+WhatsApp.
create table if not exists public.config_canales (
  id                    int primary key default 1,
  push_activo           boolean not null default true,
  email_activo          boolean not null default true,
  email_solo_sin_app    boolean not null default true,
  whatsapp_activo       boolean not null default true,
  whatsapp_solo_sin_app boolean not null default true,
  updated_at            timestamptz default now(),
  constraint config_canales_unica check (id = 1)
);
insert into public.config_canales (id) values (1) on conflict (id) do nothing;

-- ── 4) RLS (patrón authenticated, como config_mantenimiento) ──────────────────
alter table public.alerta_destinatarios    enable row level security;
alter table public.alerta_config           enable row level security;
alter table public.avisos_conductor_estado enable row level security;
alter table public.alerta_enviada          enable row level security;
alter table public.config_canales          enable row level security;

-- Helper: ¿el usuario de la sesión puede administrar la config? (admin o módulo
-- configuracion). SECURITY DEFINER para leer usuarios/permisos_usuario sin depender de
-- su RLS. El motor usa service-role (ignora RLS), así que esto solo afecta a la UI.
create or replace function public.puede_config_alertas() returns boolean
  language sql stable security definer set search_path = public as $fn$
  select exists (
    select 1 from public.usuarios u
    where u.id = auth.uid() and coalesce(u.activo, true)
      and (u.rol = 'admin' or exists (
        select 1 from public.permisos_usuario p
        where p.usuario_id = u.id and p.modulo = 'configuracion' and coalesce(p.permitido, false)))
  );
$fn$;

do $$
begin
  -- Directorio + config + canales: SOLO admin/módulo configuración (controlan mensajería
  -- saliente y el on/off de alertas de seguridad; no dejar a cualquier autenticado).
  drop policy if exists "alerta_dest_auth"     on public.alerta_destinatarios;
  drop policy if exists "alerta_config_auth"   on public.alerta_config;
  if not exists (select 1 from pg_policies where tablename='alerta_destinatarios' and policyname='alerta_dest_config') then
    create policy "alerta_dest_config" on public.alerta_destinatarios
      for all using (public.puede_config_alertas()) with check (public.puede_config_alertas());
  end if;
  if not exists (select 1 from pg_policies where tablename='alerta_config' and policyname='alerta_config_config') then
    create policy "alerta_config_config" on public.alerta_config
      for all using (public.puede_config_alertas()) with check (public.puede_config_alertas());
  end if;
  if not exists (select 1 from pg_policies where tablename='avisos_conductor_estado' and policyname='avisos_estado_auth') then
    create policy "avisos_estado_auth" on public.avisos_conductor_estado
      for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
  end if;
  if not exists (select 1 from pg_policies where tablename='alerta_enviada' and policyname='alerta_enviada_auth') then
    create policy "alerta_enviada_auth" on public.alerta_enviada
      for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
  end if;
  if not exists (select 1 from pg_policies where tablename='config_canales' and policyname='config_canales_config') then
    create policy "config_canales_config" on public.config_canales
      for all using (public.puede_config_alertas()) with check (public.puede_config_alertas());
  end if;
end$$;

-- Smoke test:
-- select clave, modo_tiempo, hora_fija, min_anticipacion, activo from public.alerta_config order by clave;
-- select * from public.alerta_destinatarios;
