-- ──────────────────────────────────────────────────────────────────────────────
-- Push nativo app pasajero: suscripciones (Web Push + FCM), dedupe de eventos
-- de viaje y throttle del motor de proximidad.
--
-- Acceso: SOLO service_role (los endpoints /api/pasajero y /api/conductor).
-- RLS habilitado SIN policies → anon/authenticated no leen ni escriben.
-- Cómo correrlo: Supabase → SQL Editor → pegar y ejecutar. Es idempotente.
-- ──────────────────────────────────────────────────────────────────────────────

-- 0) VERIFICACIÓN PREVIA (solo lectura — revisar el resultado ANTES del paso 4):
--    ¿notificaciones_enviadas tiene un CHECK que restrinja `tipo`? Si sí, el canal
--    push del recordatorio fallaría EN SILENCIO (logNotificacion no propaga error).
select c.conname, pg_get_constraintdef(c.oid) as definicion
from pg_constraint c
join pg_class t     on t.oid = c.conrelid
join pg_namespace n on n.oid = t.relnamespace
where n.nspname = 'public'
  and t.relname = 'notificaciones_enviadas'
  and c.contype = 'c';

-- 1) Suscripciones push por pasajero. Un pasajero puede tener varias (Chrome del
--    teléfono + PWA iOS + app nativa). Unicidad por endpoint (webpush) y por
--    fcm_token (fcm) — índices PARCIALES: PostgREST no puede usarlos de árbitro
--    de ON CONFLICT (misma nota que pasajeros-parada-unique.sql), así que el API
--    hace check-then-insert con captura de 23505.
create table if not exists public.push_suscripciones (
  id           bigint generated by default as identity primary key,
  pasajero_id  bigint not null references public.pasajeros(id) on delete cascade,
  tipo         text   not null check (tipo in ('webpush','fcm')),
  endpoint     text,             -- webpush
  p256dh       text,             -- webpush
  auth         text,             -- webpush
  fcm_token    text,             -- fcm
  user_agent   text,
  plataforma   text,             -- 'android-web' | 'android-app' | 'ios-pwa' | 'otro' (informativo)
  activo       boolean not null default true,
  fallos       int     not null default 0,   -- fallos consecutivos de entrega (poda en 5)
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint push_susc_payload_valido check (
    (tipo = 'webpush' and endpoint is not null and p256dh is not null and auth is not null)
    or (tipo = 'fcm' and fcm_token is not null)
  )
);
create unique index if not exists ux_push_susc_endpoint
  on public.push_suscripciones (endpoint) where endpoint is not null;
create unique index if not exists ux_push_susc_fcm
  on public.push_suscripciones (fcm_token) where fcm_token is not null;
create index if not exists ix_push_susc_pasajero_activo
  on public.push_suscripciones (pasajero_id) where activo;
alter table public.push_suscripciones enable row level security;

-- 2) Dedupe insert-once de eventos de viaje. La UNICIDAD es la lógica anti-spam:
--    el emisor intenta INSERT y si choca 23505 significa "ya se envió" (race-safe,
--    mismo patrón que embarcar_qr). parada_id/pasajero_id nulos se normalizan a 0
--    en el índice de expresión porque un UNIQUE ordinario no dedupea NULLs.
create table if not exists public.push_eventos_viaje (
  id          bigint generated by default as identity primary key,
  reserva_id  bigint not null,
  parada_id   bigint,            -- null en eventos de reserva ('salio')
  pasajero_id bigint,            -- null en eventos broadcast por parada
  evento      text not null check (evento in
              ('salio','quedan_paradas','aproximandose','llego','embarcado')),
  enviado_en  timestamptz not null default now()
);
create unique index if not exists ux_push_eventos_dedupe
  on public.push_eventos_viaje (reserva_id, evento, coalesce(parada_id, 0), coalesce(pasajero_id, 0));
create index if not exists ix_push_eventos_reserva
  on public.push_eventos_viaje (reserva_id);
alter table public.push_eventos_viaje enable row level security;

-- 3) Throttle del motor de proximidad. La memoria de módulo NO sobrevive entre
--    invocaciones serverless → el claim vive en BD: un UPDATE condicional atómico
--    gana el derecho a evaluar; los demás heartbeats pasan de largo.
create table if not exists public.push_eval_estado (
  reserva_id   bigint primary key,
  last_eval_at timestamptz not null default 'epoch'
);
alter table public.push_eval_estado enable row level security;

-- 4) CONDICIONAL — descomentar SOLO si el paso 0 mostró un CHECK sobre `tipo`
--    (ajustar el nombre del constraint al que devolvió la consulta):
-- alter table public.notificaciones_enviadas
--   drop constraint if exists notificaciones_enviadas_tipo_check;
-- alter table public.notificaciones_enviadas
--   add constraint notificaciones_enviadas_tipo_check
--   check (tipo in ('email','whatsapp','sms','push'));

-- Smoke test:
-- select count(*) from public.push_suscripciones;
-- select count(*) from public.push_eventos_viaje;
-- select count(*) from public.push_eval_estado;
